### ISSUE TITLE
Error in optickatest (line 42), myStims = metaStimulus();

### ISSUE THREAD

**Issue by psadil** [iandol/opticka#1]
Hello. A class-based approach to PTB sounds great, but I'm encountering an unexpected error trying to demo the system you've designed. Specifically, I'm running the [optickatest demo](https://github.com/iandol/opticka/blob/master/optickatest.m) with a fresh clone of the master branch (b25deac), but receive the following

```
Error using metaStimulus
The property 'verbose' restriction defined in class 'metaStimulus' must match the property definition in base class 'optickaCore'.

Error in optickatest (line 42)
myStims = metaStimulus();
```

I assume that this is an issue with my relatively old version of MATLAB (2016b). But, do you know what might be up?

Thanks,
Patrick

PTB: 3.0.14, rev 8424
MATLAB: 2016b
OS: Windows 10 Enterprise

**Comment by iandol** [comment]
@psadil sorry for the slow reply, Github is frustratingly annoying in that it does not properly notify me when issue are opened on my repositories 😢. Possibly a MATLAB version issue (OOP is a bit of a moving target as it was added late to MATLAB, but still so worth it), I may have an old version lying around and if I do I'll try to see what the issue is and what workaround I can employ.

**Comment by psadil** [comment]
@iandol, thanks for any response. Let me know if there's any more information I can provide.

**Comment by iandol** [comment]
I've pushed a small change. Basically I use type hints for properties (Property Class Validation, which is a newer feature though the MATLAB docs don't say exactly when it was introduced, but I switched from the unsupported @type style recently). When class type is specified for an abstract superclass property it may trigger this when using class validation in the child classes in older MATLABs? I've now removed the type hints in children but I don't have a 2016a to test it on (it still works on my 2019b), so if you can see if anything is improved or not. If not try removing the class validation from the superclass property (remove verbose here), and see if that works:

https://github.com/iandol/opticka/blob/master/optickaCore.m#L21

**Comment by iandol** [comment]
I actually also removed the class validation in the superclass too.

**Comment by psadil** [comment]
@iandol, thanks for looking into this. Running `optickatest` with the latest changes gave

```
Error using gratingStimulus
The property 'family' restriction defined in class 'gratingStimulus' must match the property definition in base class 'baseStimulus'.

Error in optickatest (line 46)
myStims{1}=gratingStimulus('sf',1,'contrast',0.5,'size',1,'tf',0,'angle',30,...
```
That was relieved when commenting out the `char` line in

https://github.com/iandol/opticka/blob/master/stimuli/baseStimulus.m#L15

but afterwards `optickatest.m` gave

```
Error using screenManager
Error: File: screenManager.m Line: 121 Column: 31
Unexpected MATLAB expression.

Error in baseStimulus (line 140)
				obj.sM = screenManager('verbose',false,'name','default');

Error in gratingStimulus (line 121)
			obj=obj@baseStimulus(varargin); %we call the superclass constructor first

Error in optickatest (line 46)
myStims{1}=gratingStimulus('sf',1,'contrast',0.5,'size',1,'tf',0,'angle',30,...
```

The ability to declare size restrictions must newer then my MATLAB; deleting `(1,4)` at https://github.com/iandol/opticka/blob/master/screenManager.m#L121 was sufficient for getting the demo to run. Though, it seems like I might need to find a newer MATLAB if I really wanted to take advantage of opticka.

**Comment by iandol** [comment]
So according to:

https://uk.mathworks.com/help/matlab/release-notes.html?rntext=&startrelease=R2015aSP1&endrelease=R2018b&category=advanced-software-development&groupby=release&sortby=descending&searchHighlight=validation

Abstract class validation came in 2018a and size/class validation in 2017a. For class validation there is an undocumented trick of using `@class` after property names.

https://undocumentedmatlab.com/blog/setting-class-property-types-2 

That works in 2016a, and basic class validation using the new syntax works in 2016a too as you've found, but with restrictions). But my inclination is to only use unsupported hacks when there is no official alternative. MATLAB is obviously not strongly typed, but these class annotation do help general readability and reduce potential bugs down the road. It is frustrating that because of cost, many MATLAB users cannot update regularly, and this argues for using another language entirely for the future (Python + PTB would be the dream)...

**Comment by psadil** [comment]
Makes sense. Part of the appeal in opticka was what looked like a lot of attention to class validation leading to what appeared like pretty readable code, and I certainly wouldn't advocate a backbone of undocumented (and now superseded) syntax. As you say, the real dream leaves MATLAB behind. Thanks anyway, and maybe I'll be back if our lab happens to upgrade. 

Feel free to close this issue (though, could the minimum MATLAB version be updated in the README?)

best

**Comment by iandol** [comment]
Thanks, I will update the README!
